In [2]:
#Creating arrays
#manipulating arrays
#Combining arrays
#Linear algebra with arrays

import numpy as np

In [2]:
np.random.randint(5, size = 7)

array([2, 1, 0, 3, 0, 4, 1])

In [5]:
np.random.randint(2, 10, size = (3,2))

array([[8, 8],
       [7, 6],
       [7, 2]])

In [12]:
np.random.random(8)

array([0.70625262, 0.15722492, 0.11213643, 0.74875088, 0.76811135,
       0.83365827, 0.60606468, 0.95658193])

In [14]:
print(np.random.randn(100).mean())
print(np.random.randn(100).std())

0.08646787932367507
0.9363157589881593


In [16]:
#Matrix with ones and zeros
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.full((1,1), 5)

array([[5]])

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
#Identity Matrix
print(np.eye(3))
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
print(np.arange(7))
print (np.arange(1,7))

[0 1 2 3 4 5 6]
[1 2 3 4 5 6]


In [27]:
print(np.arange(0,10,2))
print(np.arange(30,100,5))

[0 2 4 6 8]
[30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [29]:
np.full((3,4), 8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [30]:
np.full((3,4), 8, dtype = 'float')

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [32]:
#MANIPULATING ARRAYS
A = np.random.randint(5, size = (3,4))
A

array([[1, 3, 3, 2],
       [0, 0, 0, 2],
       [1, 0, 1, 3]])

In [33]:
A.ravel()

array([1, 3, 3, 2, 0, 0, 0, 2, 1, 0, 1, 3])

In [35]:
A.ravel(order = 'F')

array([1, 0, 1, 3, 0, 0, 3, 0, 1, 2, 2, 3])

In [36]:
A.shape

(3, 4)

In [38]:
A.size

12

In [40]:
A.reshape(4,3)

array([[1, 3, 3],
       [2, 0, 0],
       [0, 2, 1],
       [0, 1, 3]])

In [41]:
A.reshape(2,6)

array([[1, 3, 3, 2, 0, 0],
       [0, 2, 1, 0, 1, 3]])

In [42]:
#Letting numpy figure out the size in every dimension
print(A.reshape(-1,3))
print(A.reshape(1,-1))

[[1 3 3]
 [2 0 0]
 [0 2 1]
 [0 1 3]]
[[1 3 3 2 0 0 0 2 1 0 1 3]]


In [44]:
A

array([[1, 3, 3, 2],
       [0, 0, 0, 2],
       [1, 0, 1, 3]])

In [45]:
A.transpose()

array([[1, 0, 1],
       [3, 0, 0],
       [3, 0, 1],
       [2, 2, 3]])

In [48]:
A = np.random.randint(5, size=(4,3))
np.vsplit(A, 2)

[array([[4, 4, 1],
        [4, 2, 4]]),
 array([[1, 3, 3],
        [1, 3, 0]])]

In [49]:
A = np.random.randint(5, size=(6,3))  #Vertical Split
np.vsplit(A, 3)[0]

array([[2, 0, 1],
       [0, 1, 1]])

In [50]:
a = np.array([[1,1,1,3,4,5,9,10]])  #Horizontal split
np.hsplit(a, 2)

[array([[1, 1, 1, 3]]), array([[ 4,  5,  9, 10]])]

In [51]:
A = np.random.randint(5, size = (6,3))
np.hsplit(A, 3)[0]

array([[0],
       [0],
       [1],
       [1],
       [4],
       [0]])

In [52]:
np.hsplit(A, 3)[0].shape

(6, 1)

In [53]:
#COMBINING ARRAYS

#Concatenate
a = np.array([1,2,3,4])
b = np.array([3,3,3])
np.concatenate((a,b))

array([1, 2, 3, 4, 3, 3, 3])

In [54]:
a = np.array([1,2,3,4])
b = np.array([3,3,3,3])

np.concatenate((a.reshape(-1,1),b.reshape(-1,1)), axis = 1)

array([[1, 3],
       [2, 3],
       [3, 3],
       [4, 3]])

In [55]:
#Vstack

a = np.array([1,2,3,4])
b = np.array([3,3,3,3])
c = np.array([0,1,5,6])

np.vstack((a,b,c))

array([[1, 2, 3, 4],
       [3, 3, 3, 3],
       [0, 1, 5, 6]])

In [56]:
A = np.random.randint(5, size = (2,2,2))
B = np.random.randint(5, size = (2,2,2))
C = np.random.randint(5, size = (2,2,2))

np.vstack((A,B,C))

array([[[2, 3],
        [4, 4]],

       [[3, 3],
        [0, 0]],

       [[1, 1],
        [3, 0]],

       [[3, 2],
        [2, 4]],

       [[2, 3],
        [3, 4]],

       [[1, 2],
        [3, 3]]])

In [59]:
a = np.array([1,2,3,4]).reshape(-1,1)
b = np.array([3,3,3,3]).reshape(-1,1)
c = np.array([0,1,5,6]).reshape(-1,1)

np.hstack((a,b,c))

array([[1, 3, 0],
       [2, 3, 1],
       [3, 3, 5],
       [4, 3, 6]])

In [62]:
#linear Algebra With Numpy Arrays(numpy.linalg)

#Det
A = np.random.randint(5, size=(3,3))
A

array([[3, 4, 1],
       [2, 1, 4],
       [3, 4, 4]])

In [63]:
np.linalg.det(A)

-15.000000000000007

In [66]:
#Inverse(inv)

np.linalg.inv(A)

array([[ 0.8       ,  0.8       , -1.        ],
       [-0.26666667, -0.6       ,  0.66666667],
       [-0.33333333,  0.        ,  0.33333333]])

In [67]:
#Eig(EIGENVALUES, RIGHT EIGENVECTORS)

np.linalg.eig(A)

(array([ 8.72015325,  1.        , -1.72015325]),
 array([[ 0.47542448,  0.8479983 ,  0.60317434],
        [ 0.49868364, -0.31799936, -0.76672214],
        [ 0.7247663 , -0.42399915,  0.21981327]]))

In [68]:
#Dot (Calculates the Dot Product of two vectors)

a = np.array([1,2,3,4])
b = np.array([2,2,2,2])
np.dot(a,b)

20

In [69]:
#20 Matmul (It performs matrix Multiplication)

A = ([[1,2], 
      [3,4]])
B = ([[3,4],
      [3,1]])
np.matmul(A,B)

array([[ 9,  6],
       [21, 16]])