In [23]:
import numpy as np

In [3]:
my_list = [1,2,3,4,5]

In [5]:
my_numpy_list = np.array(my_list)
my_numpy_list

array([1, 2, 3, 4, 5])

In [6]:
second_list = [[1,2,3],[5,4,1],[3,6,7]]
new_2d_arr = np.array(second_list)
new_2d_arr

array([[1, 2, 3],
       [5, 4, 1],
       [3, 6, 7]])

In [9]:
my_list = np.arange(10)

my_list = np.arange(0,10)

In [10]:
my_list = np.arange(0,11,2)

In [30]:
my_zeros = np.zeros(7)
my_zeros
my_ones = np.ones(5)
my_ones
two_d = np.zeros((3,5))
two_d

array([1., 1., 1., 1., 1.])

In [25]:
lin_arr = np.linspace(1, 3, 15)
lin_arr

array([1.        , 1.14285714, 1.28571429, 1.42857143, 1.57142857,
       1.71428571, 1.85714286, 2.        , 2.14285714, 2.28571429,
       2.42857143, 2.57142857, 2.71428571, 2.85714286, 3.        ])

In [15]:
np.random.rand(5) #using rand()

array([0.37869618, 0.80737569, 0.57496312, 0.2711573 , 0.12604269])

In [33]:
np.random.rand(5, 4) #using rand()

array([[0.72218829, 0.22835623, 0.42932112, 0.65310149],
       [0.04436796, 0.25835789, 0.11199085, 0.01552113],
       [0.29702584, 0.7872337 , 0.35763251, 0.07679085],
       [0.03186011, 0.16719322, 0.75794151, 0.80910131],
       [0.86694217, 0.58432803, 0.40604262, 0.06502422]])

In [ ]:
np.random.randn(5) #using randn()

In [34]:
np.random.randint(20) #Also using randint()

6

In [35]:
np.random.randint(2,20)

11

In [40]:
np.random.randint(2,20,7)

array([ 7,  9, 19,  4, 12,  9, 13])

In [16]:
Arr = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
Arr.shape

(3, 3)

In [12]:
A = np.arange(1,11)
A[8]

9

In [41]:
arr = np.random.rand(25)
arr.reshape(5,5)

array([[0.27862817, 0.07260998, 0.5002254 , 0.14359392, 0.03137461],
       [0.53800743, 0.57031176, 0.36185481, 0.01328368, 0.3277159 ],
       [0.58273469, 0.71266416, 0.86609036, 0.61089769, 0.13829415],
       [0.48684717, 0.60958951, 0.82344721, 0.43189565, 0.15563544],
       [0.02242656, 0.06833472, 0.30550501, 0.16314863, 0.47820252]])

In [50]:
arr_2 = np.random.randint(0, 20, 10)
arr_2.max()

18

In [51]:
arr_2.min()

1

In [55]:
arr_2.argmax() #This shows the index of the highest value in the array
arr_2.argmin() #This shows the index of the lowest value in the array

9

In [65]:
arr.shape

(25,)

In [61]:
my_array = np.arange(0,11)
my_array [8]

8

In [62]:
my_array[2:6]  #This returns everything from index 2 to 6 (exclusive)

array([2, 3, 4, 5])

In [63]:
my_array[:6]
my_array[5:]

array([ 5,  6,  7,  8,  9, 10])

In [67]:
two_d_arr = np.array([[10,20,30],
                      [40,50,60],
                      [70,80,90]])
two_d_arr[1][2]

60

In [68]:
two_d_arr[:1, :2]

array([[10, 20]])

In [70]:
two_d_arr[:2, 1:]

array([[20, 30],
       [50, 60]])

In [71]:
two_d_arr [:2, :2]

array([[10, 20],
       [40, 50]])

In [73]:
two_d_arr[0] #This grabs the row Zero of the array
two_d_arr[:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [74]:
new_arr = np.arange(5,15)
new_arr > 10

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [76]:
bool_arr = new_arr > 10
new_arr[bool_arr]

array([11, 12, 13, 14])

In [77]:
new_arr[(new_arr>6) & (new_arr<10)]

array([7, 8, 9])

In [83]:
my_array = np.arange(0,11)
my_array[0:3] = 50

In [91]:
arr = np.arange(1,11)
arr*arr
arr-arr
arr+arr
arr/arr
arr + 50  #Performing scalar operation on the array, this add 50 to every element in the array

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [111]:
#Performing universal functions such as square roots, exponenetials,trig and so on.
np.sqrt(arr)
np.exp(arr)
np.sin(arr)
np.cos(arr)
np.tan(arr)
np.log(arr)
print(np.sum(arr))
print(np.std(arr))

55
2.8722813232690143


In [108]:
#Grabing the sum ofcolumns or row in a 2-d array
mat = np.arange(1,26).reshape(5,5)

mat.sum()
mat.sum(axis = 0)
mat.sum(axis = 1)

array([ 15,  40,  65,  90, 115])