In [21]:
import numpy as np
a = [1,2,3,4,5,6,7,8,9]
A = np.array([1,2,3,4,5,6,7,8,9])
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [4]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

In [3]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [11]:
data = np.arange(0,10)
data.shape

(10,)

In [8]:
data.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
A = [[2,3,4,
      5,6,7,
      8,9,10]]
np.sum(A)

54

In [24]:
A = [[2,3,4]
      ,[5,6,7],
      [8,9,10]]
np.sum(A, axis = 1)

array([ 9, 18, 27])

In [23]:
import numpy as np
A = [[2,3,4],
      [5,6,7],
      [8,9,10]]
np.sum(A,axis=0)

array([15, 18, 21])

In [23]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
 np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
D = np.arange(1,10).reshape(3,3)
D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
I = np.eye (3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
Q = np.dot(D,I)
Q

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [38]:
np.sum(Q, axis = 1) #Sum along row

array([ 6., 15., 24.])

In [39]:
np.sum(Q, axis = 0) #Sum along column

array([12., 15., 18.])